### ISSUE TITLE
Incorrect Git repository's history management

### ISSUE THREAD

**Issue by castarco** [mulesoft/api-workbench#169]
I think the way this git repository is managed is incorrect. Not having access to the development historic data is problematic, because we can't know what to expect about this project.

Users are unable to know anything about the activity level, this could affect to some company schedules, and makes very difficult to audit the code and the code changes, among other potential problems.

**Comment by sichvoge** [comment]
Hi thanks for your feedback. We know that the current state is far from perfect and its something that we are working on. In the past we used a single project to handle the lifecycle for different projects that we worked on for the alpha version of the RAML 1.0 specification such as the workbench, websites, and our parsers. That way we could rapidly implement changes for 1.0 during its development. Now that GA is getting closer most of the projects has been already externalized and are available as separate public sources / repositories such as the JS and Java parser. Our next item is separating the Workbench from its original project as it is not necessary to keep all in one, again because the RAML 1.0 spec goes GA soon. This will happen after the GA since resources are currently allocated for the Java and JS parser to support all new features around 1.0.

Please bear with us a bit longer.

**Comment by sichvoge** [comment]
Thank you for waiting. Happy to announce that the code is available in our [code branch](https://github.com/mulesoft/api-workbench/tree/code) now. The plan is to tidy up a bit more and fix some issues with regards to that ticket [here](https://github.com/mulesoft/api-workbench/issues/170), before merging it to our branch.
