### ISSUE TITLE
Atom API Workench Console Not Showing Response Body

### ISSUE THREAD

**Issue by qutwala** [mulesoft/api-workbench#90]
Hi,

![capture](https://cloud.githubusercontent.com/assets/5105752/12179197/2739f926-b57e-11e5-8a0e-6a7948d81c1c.PNG)

I have following RAML:

        #%RAML 1.0
        title: API For ISO3166 Module
        version: v1
        baseUri: http://api.example.com/{version}/
        mediaType: application/json
        /countries:
          displayName: Countries endpoint
          description: List countries
          get:
            responses:
              200:
                body:
                  application/json:

In console when i run that GET method for this resourse it returns nothing though in browser or in any other client it returns:

    { 'id' : 1 }

It's some kind of a bug or maybe i have some mistake made in my syntax?

OS: windows 10

Thanks.

**Comment by qutwala** [comment]
Maybe i'm missing something, but i can't expand response body, it looks something like this every time when response is something more than `{  'id' : 1 }` :

![capture2](https://cloud.githubusercontent.com/assets/5105752/12295285/d8c89f24-ba08-11e5-9d6a-b1cac6d3f195.PNG)

**Comment by blakeembrey** [comment]
Sorry about not updating, it was closed via a linked issue from a private repository which results in a terrible experience here (because you obviously can't see the linked issue). The request issue was resolved by not to parsing response data (previously it was parsing to JSON, which wouldn't render as a string).
